-- ============================================================================
--  01_schema.sql  (PostgreSQL)  — REFERENCIA
--
--  La forma CANÓNICA de crear el esquema es ejecutar `python seed.py`, que
--  llama a db.create_all() y genera todas las tablas desde los modelos
--  SQLAlchemy (tipos, PK, FK, UNIQUE, índices) de forma reproducible.
--
--  Este script se mantiene como referencia legible del modelo físico y para
--  instalaciones manuales sin Python. Es idempotente (CREATE ... IF NOT EXISTS).
--
--  Mapeo de tipos respecto a SQL Server:
--    INT IDENTITY(1,1)   -> INTEGER GENERATED BY DEFAULT AS IDENTITY
--    BIT                 -> BOOLEAN
--    DATETIME/DATETIME2  -> TIMESTAMP           (sin zona; se guarda en UTC)
--    NVARCHAR(MAX)       -> TEXT
--    NVARCHAR(n)         -> VARCHAR(n)
--    DECIMAL/NUMERIC     -> NUMERIC
-- ============================================================================

-- ── usuarios ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS usuarios (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR(100) NOT NULL,
    apellido          VARCHAR(100) NOT NULL,
    email             VARCHAR(150) NOT NULL UNIQUE,
    password_hash     VARCHAR(255) NOT NULL,
    rol               VARCHAR(20)  NOT NULL DEFAULT 'comercial',
    activo            BOOLEAN      DEFAULT TRUE,
    id_empresa        INTEGER      DEFAULT 0,
    totp_secret       VARCHAR(255),
    totp_estado       VARCHAR(20)  DEFAULT 'no_configurado',
    totp_fecha_config TIMESTAMP,
    totp_fecha_reset  TIMESTAMP,
    creado_en         TIMESTAMP    DEFAULT (now() AT TIME ZONE 'utc'),
    actualizado_en    TIMESTAMP    DEFAULT (now() AT TIME ZONE 'utc')
);

-- ── empresas ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS empresas (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                VARCHAR(150) NOT NULL,
    ruc                   VARCHAR(30)  UNIQUE,
    direccion             VARCHAR(255),
    telefono              VARCHAR(30),
    email                 VARCHAR(150),
    activo                BOOLEAN DEFAULT TRUE,
    consultas_habilitadas BOOLEAN DEFAULT TRUE,
    motivo_bloqueo        VARCHAR(50),
    fecha_bloqueo         TIMESTAMP,
    fecha_desbloqueo      TIMESTAMP,
    creado_en             TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
);

-- ── paises / departamento / ciudad ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS paises (
    id_pais     VARCHAR(10) PRIMARY KEY,
    nombre_pais VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS departamento (
    id_departamento     INTEGER PRIMARY KEY,
    nombre_departamento VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ciudad (
    id_ciudad       INTEGER PRIMARY KEY,
    nombre_ciudad   VARCHAR(100) NOT NULL,
    id_departamento INTEGER NOT NULL REFERENCES departamento(id_departamento)
);

-- ── clientes ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS clientes (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_doc         VARCHAR(10) NOT NULL,
    num_doc          VARCHAR(20) NOT NULL UNIQUE,
    nombre           VARCHAR(100) NOT NULL,
    apellido         VARCHAR(100),
    email            VARCHAR(150),
    telefono         VARCHAR(20),
    direccion        VARCHAR(255),
    fecha_nacimiento DATE,
    nacionalidad     VARCHAR(10) REFERENCES paises(id_pais),
    id_ciudad        INTEGER REFERENCES ciudad(id_ciudad),
    estado           VARCHAR(20) DEFAULT 'activo',
    creado_por       INTEGER REFERENCES usuarios(id),
    creado_en        TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
);

-- ── cliente_empresa ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS cliente_empresa (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL REFERENCES clientes(id),
    id_empresa INTEGER NOT NULL REFERENCES empresas(id),
    estado     VARCHAR(20) DEFAULT 'activo',
    creado_en  TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT uq_cliente_empresa UNIQUE (id_cliente, id_empresa)
);

-- ── criterios ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS criterios (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    peso        NUMERIC(5,2) NOT NULL CHECK (peso > 0 AND peso <= 100),
    activo      BOOLEAN DEFAULT TRUE
);

-- ── evaluaciones / evaluacion_detalle ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS evaluaciones (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id    INTEGER NOT NULL REFERENCES clientes(id),
    evaluador_id  INTEGER NOT NULL REFERENCES usuarios(id),
    fecha         TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
    puntaje_total NUMERIC(5,2),
    resultado     VARCHAR(20),
    observaciones TEXT,
    estado        VARCHAR(20) DEFAULT 'pendiente'
);

CREATE TABLE IF NOT EXISTS evaluacion_detalle (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id INTEGER NOT NULL REFERENCES evaluaciones(id) ON DELETE CASCADE,
    criterio_id   INTEGER NOT NULL REFERENCES criterios(id),
    valor         NUMERIC(5,2) NOT NULL CHECK (valor >= 0 AND valor <= 100),
    comentario    VARCHAR(255)
);

-- ── documentos ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS documentos (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id     INTEGER NOT NULL REFERENCES clientes(id),
    tipo           VARCHAR(50)  NOT NULL,
    nombre_archivo VARCHAR(255) NOT NULL,
    ruta           VARCHAR(500) NOT NULL,
    subido_por     INTEGER REFERENCES usuarios(id),
    subido_en      TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
);

-- ── motor_reglas / reglas ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS motor_reglas (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(100) NOT NULL,
    version          VARCHAR(20)  NOT NULL DEFAULT '1.0',
    descripcion      VARCHAR(255),
    activo           BOOLEAN DEFAULT TRUE,
    creado_por       INTEGER REFERENCES usuarios(id),
    id_empresa_motor INTEGER DEFAULT 0,
    creado_en        TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS reglas (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    motor_id         INTEGER NOT NULL REFERENCES motor_reglas(id) ON DELETE CASCADE,
    nombre           VARCHAR(100) NOT NULL,
    descripcion      VARCHAR(255),
    parametro        VARCHAR(50)  NOT NULL,
    operador         VARCHAR(10)  NOT NULL,
    valor_referencia VARCHAR(100) NOT NULL,
    tipo_valor       VARCHAR(20)  NOT NULL DEFAULT 'numerico',
    peso_puntos      NUMERIC(6,2) NOT NULL,
    es_determinante  BOOLEAN DEFAULT FALSE,
    activo           BOOLEAN DEFAULT TRUE,
    orden            INTEGER DEFAULT 0
);

-- ── historial_crediticio ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS historial_crediticio (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id             INTEGER NOT NULL UNIQUE REFERENCES clientes(id),
    fuente_externa         VARCHAR(100),
    score_externo          NUMERIC(6,2),
    cantidad_atrasos       INTEGER DEFAULT 0,
    deuda_total_sistema    NUMERIC(14,2) DEFAULT 0,
    historial_pagos        VARCHAR(20) DEFAULT 'sin_historial',
    en_lista_negra         BOOLEAN DEFAULT FALSE,
    nivel_endeudamiento    NUMERIC(5,2) DEFAULT 0,
    meses_empleo_actual    INTEGER DEFAULT 0,
    tipo_empleo            VARCHAR(50),
    referencias_personales VARCHAR(20) DEFAULT 'no_verificadas',
    fecha_consulta         TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
    actualizado_en         TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
);

-- ── evaluacion_riesgo / resultado_detalle / detalle_operacion ────────────────
CREATE TABLE IF NOT EXISTS evaluacion_riesgo (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id            INTEGER NOT NULL REFERENCES clientes(id),
    motor_id              INTEGER NOT NULL REFERENCES motor_reglas(id),
    usuario_id            INTEGER NOT NULL REFERENCES usuarios(id),
    fecha_analisis        TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
    score_final           NUMERIC(6,2),
    score_maximo          NUMERIC(6,2),
    categoria_riesgo      VARCHAR(20),
    estado                VARCHAR(20) DEFAULT 'completado',
    observaciones         TEXT,
    regla_determinante_id INTEGER REFERENCES reglas(id),
    id_empresa            INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS resultado_detalle (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id    INTEGER NOT NULL REFERENCES evaluacion_riesgo(id) ON DELETE CASCADE,
    regla_id         INTEGER NOT NULL REFERENCES reglas(id),
    cumplido         BOOLEAN NOT NULL,
    valor_evaluado   VARCHAR(100),
    puntos_obtenidos NUMERIC(6,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS detalle_operacion (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id    INTEGER NOT NULL REFERENCES evaluacion_riesgo(id) ON DELETE CASCADE,
    tipo_propiedad   VARCHAR(50) NOT NULL,
    valor_propiedad  NUMERIC(14,2) NOT NULL,
    monto_solicitado NUMERIC(14,2) NOT NULL,
    plazo_meses      INTEGER NOT NULL,
    ubicacion        VARCHAR(255),
    destino          VARCHAR(50)
);

-- ── lista_negra_onu (referencia externa; sin FK) ─────────────────────────────
CREATE TABLE IF NOT EXISTS lista_negra_onu (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro         VARCHAR(20),
    nombre           VARCHAR(150),
    apellido         VARCHAR(150),
    cargo            VARCHAR(500),
    fecha_nacimiento VARCHAR(200),
    nacionalidad     VARCHAR(200),
    num_identidad    VARCHAR(300),
    num_pasaporte    VARCHAR(500),
    otros            TEXT
);

-- ── facturación ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS planes (
    id                             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                         VARCHAR(50) NOT NULL UNIQUE,
    cantidad_reportes_incluidos    INTEGER NOT NULL,
    precio_plan                    NUMERIC(14,0) NOT NULL,
    precio_reporte_incluido        NUMERIC(14,0) NOT NULL,
    precio_reporte_sobre_facturado NUMERIC(14,0) NOT NULL,
    activo                         BOOLEAN DEFAULT TRUE,
    creado_en                      TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
    actualizado_en                 TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS empresa_planes (
    id                             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id                     INTEGER NOT NULL REFERENCES empresas(id),
    plan_id                        INTEGER NOT NULL REFERENCES planes(id),
    fecha_inicio                   TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    fecha_fin                      TIMESTAMP,
    estado                         VARCHAR(20) DEFAULT 'activo',
    precio_plan_contratado         NUMERIC(14,0) NOT NULL,
    cantidad_reportes_incluidos    INTEGER NOT NULL,
    precio_reporte_sobre_facturado NUMERIC(14,0) NOT NULL,
    creado_en                      TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS periodos_facturacion (
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id                  INTEGER NOT NULL REFERENCES empresas(id),
    empresa_plan_id             INTEGER NOT NULL REFERENCES empresa_planes(id),
    anio                        INTEGER NOT NULL,
    mes                         INTEGER NOT NULL,
    fecha_inicio                TIMESTAMP NOT NULL,
    fecha_fin                   TIMESTAMP NOT NULL,
    cantidad_reportes_incluidos INTEGER NOT NULL,
    reportes_consumidos         INTEGER DEFAULT 0,
    reportes_sobre_facturados   INTEGER DEFAULT 0,
    monto_plan                  NUMERIC(14,0) DEFAULT 0,
    monto_sobre_facturado       NUMERIC(14,0) DEFAULT 0,
    monto_total                 NUMERIC(14,0) DEFAULT 0,
    monto_pagado                NUMERIC(14,0) DEFAULT 0,
    saldo_pendiente             NUMERIC(14,0) DEFAULT 0,
    estado                      VARCHAR(20) DEFAULT 'PENDIENTE',
    CONSTRAINT uq_periodo_empresa_mes UNIQUE (empresa_id, anio, mes)
);

CREATE TABLE IF NOT EXISTS consumo_reportes (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id             INTEGER NOT NULL REFERENCES empresas(id),
    usuario_id             INTEGER NOT NULL,
    evaluacion_id          INTEGER NOT NULL,
    periodo_facturacion_id INTEGER NOT NULL REFERENCES periodos_facturacion(id),
    tipo_consumo           VARCHAR(20) NOT NULL,
    precio_unitario        NUMERIC(14,0) NOT NULL,
    fecha_consumo          TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT uq_consumo_evaluacion UNIQUE (evaluacion_id, empresa_id)
);

CREATE TABLE IF NOT EXISTS pagos (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id             INTEGER NOT NULL REFERENCES empresas(id),
    periodo_facturacion_id INTEGER NOT NULL REFERENCES periodos_facturacion(id),
    monto                  NUMERIC(14,0) NOT NULL,
    proveedor              VARCHAR(50) DEFAULT 'TEST',
    referencia_externa     VARCHAR(100),
    estado                 VARCHAR(20) DEFAULT 'PENDIENTE',
    metodo_pago            VARCHAR(50),
    observacion            VARCHAR(255),
    fecha_inicio           TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
    fecha_confirmacion     TIMESTAMP
);

CREATE TABLE IF NOT EXISTS historial_empresa_planes (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id        INTEGER NOT NULL REFERENCES empresas(id),
    plan_id           INTEGER NOT NULL REFERENCES planes(id),
    plan_nombre       VARCHAR(50) NOT NULL,
    precio_plan       NUMERIC(14,0) NOT NULL,
    cantidad_reportes INTEGER NOT NULL,
    precio_sobre_fact NUMERIC(14,0) NOT NULL,
    fecha_desde       TIMESTAMP NOT NULL,
    fecha_hasta       TIMESTAMP,
    cambiado_por      INTEGER REFERENCES usuarios(id),
    fecha_cambio      TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
);

-- ── auditoria (bitácora; sin FK a propósito) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS auditoria (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         INTEGER,
    usuario_nombre     VARCHAR(150),
    id_empresa         INTEGER,
    tipo_evento        VARCHAR(30) NOT NULL,
    accion             VARCHAR(50) NOT NULL,
    modulo             VARCHAR(50),
    entidad            VARCHAR(50),
    registro_id        VARCHAR(50),
    resultado          VARCHAR(20) DEFAULT 'EXITO',
    ip                 VARCHAR(50),
    info_adicional     TEXT,
    valores_anteriores TEXT,
    valores_nuevos     TEXT,
    fecha              TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
);

-- ── scoring_* (core de scoring) ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS scoring_modelo (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL,
    version     VARCHAR(20)  NOT NULL DEFAULT '1.0',
    descripcion VARCHAR(500),
    id_empresa  INTEGER NOT NULL DEFAULT 0,
    activo      BOOLEAN DEFAULT TRUE,
    creado_en   TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS scoring_factor (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo_id    INTEGER NOT NULL REFERENCES scoring_modelo(id),
    codigo       VARCHAR(50)  NOT NULL,
    nombre       VARCHAR(100) NOT NULL,
    descripcion  VARCHAR(500),
    tipo_dato    VARCHAR(20)  NOT NULL DEFAULT 'numerico',
    tipo_persona VARCHAR(10)  NOT NULL DEFAULT 'AMBOS',
    categoria    VARCHAR(20)  DEFAULT 'principal',
    obligatorio  BOOLEAN DEFAULT TRUE,
    activo       BOOLEAN DEFAULT TRUE,
    orden        INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS scoring_catalogo (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factor_id INTEGER NOT NULL REFERENCES scoring_factor(id),
    valor     VARCHAR(100) NOT NULL,
    etiqueta  VARCHAR(100) NOT NULL,
    orden     INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS scoring_regla (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factor_id   INTEGER NOT NULL REFERENCES scoring_factor(id),
    nombre      VARCHAR(100) NOT NULL,
    operador    VARCHAR(10)  NOT NULL,
    valor_min   VARCHAR(100),
    valor_max   VARCHAR(100),
    nivel       VARCHAR(10)  NOT NULL,
    peso        NUMERIC(8,2) NOT NULL,
    explicacion VARCHAR(500),
    orden       INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS scoring_umbral (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo_id   INTEGER NOT NULL REFERENCES scoring_modelo(id),
    nivel       VARCHAR(10)  NOT NULL,
    score_min   NUMERIC(8,2) NOT NULL,
    score_max   NUMERIC(8,2) NOT NULL,
    descripcion VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS scoring_evaluacion (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id         INTEGER NOT NULL,
    modelo_id          INTEGER NOT NULL REFERENCES scoring_modelo(id),
    modelo_version     VARCHAR(20) NOT NULL,
    usuario_id         INTEGER NOT NULL,
    id_empresa         INTEGER NOT NULL DEFAULT 0,
    tipo_persona       VARCHAR(10) NOT NULL,
    fecha              TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
    score_total        NUMERIC(8,2) NOT NULL,
    clasificacion      VARCHAR(10)  NOT NULL,
    explicacion        TEXT,
    factores_evaluados INTEGER DEFAULT 0,
    factores_sin_dato  INTEGER DEFAULT 0,
    estado             VARCHAR(20) DEFAULT 'completa'
);

CREATE TABLE IF NOT EXISTS scoring_detalle (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id  INTEGER NOT NULL REFERENCES scoring_evaluacion(id),
    factor_codigo  VARCHAR(50)  NOT NULL,
    factor_nombre  VARCHAR(100) NOT NULL,
    categoria      VARCHAR(20),
    valor_original VARCHAR(200),
    estado         VARCHAR(20)  NOT NULL,
    regla_aplicada VARCHAR(100),
    nivel          VARCHAR(10),
    peso           NUMERIC(8,2) DEFAULT 0,
    explicacion    VARCHAR(500)
);

-- ── índices ──────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS ix_clientes_num_doc        ON clientes(num_doc);
CREATE INDEX IF NOT EXISTS ix_clientes_estado         ON clientes(estado);
CREATE INDEX IF NOT EXISTS ix_evaluaciones_cliente    ON evaluaciones(cliente_id);
CREATE INDEX IF NOT EXISTS ix_evaluaciones_resultado  ON evaluaciones(resultado);
CREATE INDEX IF NOT EXISTS ix_evaluaciones_fecha      ON evaluaciones(fecha DESC);
CREATE INDEX IF NOT EXISTS ix_eval_detalle_evaluacion ON evaluacion_detalle(evaluacion_id);
CREATE INDEX IF NOT EXISTS ix_evalriesgo_cliente      ON evaluacion_riesgo(cliente_id);
CREATE INDEX IF NOT EXISTS ix_evalriesgo_categoria    ON evaluacion_riesgo(categoria_riesgo);
CREATE INDEX IF NOT EXISTS ix_evalriesgo_fecha        ON evaluacion_riesgo(fecha_analisis DESC);
CREATE INDEX IF NOT EXISTS ix_reglas_motor            ON reglas(motor_id);
CREATE INDEX IF NOT EXISTS ix_detop_evaluacion        ON detalle_operacion(evaluacion_id);
